### ISSUE TITLE
Unknown error connecting with Helvar router

### ISSUE THREAD

**Issue by 1aranzant** [tomplayford/homeassistant_helvar#1]
Hey ! I'm trying to connect to both my Helvar digidim 905s, but both of them return the following error:
What could the issue be?
Thanks for your work !

```
2024-05-31 23:32:23.502 ERROR (MainThread) [custom_components.helvar.config_flow] Creating Helvar config entry
NoneType: None
2024-05-31 23:32:28.589 ERROR (MainThread) [custom_components.helvar.router] Unknown error connecting with Helvar router at 192.168.3.10
Traceback (most recent call last):
File "/config/custom_components/helvar/router.py", line 43, in async_setup
await router.initialize()
File "/usr/local/lib/python3.12/site-packages/aiohelvar/router.py", line 207, in initialize
await self.get_scenes()
File "/usr/local/lib/python3.12/site-packages/aiohelvar/router.py", line 222, in get_scenes
await get_scenes(self, self.groups)
File "/usr/local/lib/python3.12/site-packages/aiohelvar/scenes.py", line 74, in get_scenes
parts = response.result.strip("@").split("@")
^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strip'
2024-05-31 23:32:29.686 ERROR (MainThread) [aiohelvar.router] Request command >V:2,C:100,@0.1.1# triggered an error back from the router: !V:2,C:100,@0.1.1=9#.
2024-05-31 23:32:29.696 ERROR (MainThread) [aiohelvar.router] Request command >V:2,C:100,@0.1.2# triggered an error back from the router: !V:2,C:100,@0.1.2=9#.
2024-05-31 23:32:29.707 ERROR (MainThread) [aiohelvar.router] Request command >V:2,C:100,@0.1.3# triggered an error back from the router: !V:2,C:100,@0.1.3=9#.
2024-05-31 23:32:29.709 ERROR (MainThread) [aiohelvar.router] Request command >V:2,C:100,@0.1.4# triggered an error back from the router: !V:2,C:100,@0.1.4=9#.
```

**Comment by benwallacestock** [comment]
I am also getting the error described above. @1aranzant did you end up getting this working??
```
This error originated from a custom integration.

Logger: custom_components.helvar.router
Source: custom_components/helvar/router.py:43
integration: HelvarNet
First occurred: 12:20:40 PM (1 occurrences)
Last logged: 12:20:40 PM

Unknown error connecting with Helvar router at 10.254.1.1
Traceback (most recent call last):
  File "/config/custom_components/helvar/router.py", line 43, in async_setup
    await router.initialize()
  File "/usr/local/lib/python3.12/site-packages/aiohelvar/router.py", line 207, in initialize
    await self.get_scenes()
  File "/usr/local/lib/python3.12/site-packages/aiohelvar/router.py", line 222, in get_scenes
    await get_scenes(self, self.groups)
  File "/usr/local/lib/python3.12/site-packages/aiohelvar/scenes.py", line 74, in get_scenes
    parts = response.result.strip("@").split("@")
            ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strip'

```

**Comment by 1aranzant** [comment]
@benwallacestock nop still nothing...

**Comment by tomplayford** [comment]
This is a parsing bug, hopefully fixed but without the ability to replicate your set up, I con't be sure. 

It'll either work for you now or you'll get a different (better?) error. Please share it here if you do. Going to close this for now.

**Comment by 1aranzant** [comment]
Hey ! Sadly I still have the following error, even after updating to 0.2.0. 

```
`2025-07-21 16:31:51.747 ERROR (MainThread) [custom_components.helvar.config_flow] Creating Helvar config entry
NoneType: None
2025-07-21 16:31:56.846 ERROR (MainThread) [custom_components.helvar.router] Unknown error connecting with Helvar router at 192.168.0.10
Traceback (most recent call last):
  File "/config/custom_components/helvar/router.py", line 43, in async_setup
    await router.initialize()
  File "/usr/local/lib/python3.13/site-packages/aiohelvar/router.py", line 207, in initialize
    await self.get_scenes()
  File "/usr/local/lib/python3.13/site-packages/aiohelvar/router.py", line 222, in get_scenes
    await get_scenes(self, self.groups)
  File "/usr/local/lib/python3.13/site-packages/aiohelvar/scenes.py", line 74, in get_scenes
    parts = response.result.strip("@").split("@")
            ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strip'
2025-07-21 16:31:57.969 ERROR (MainThread) [aiohelvar.router] Request command >V:2,C:100,@0.1.1# triggered an error back from the router: !V:2,C:100,@0.1.1=10#.
2025-07-21 16:31:57.987 ERROR (MainThread) [aiohelvar.router] Request command >V:2,C:100,@0.1.2# triggered an error back from the router: !V:2,C:100,@0.1.2=10#.
2025-07-21 16:31:58.000 ERROR (MainThread) [aiohelvar.router] Request command >V:2,C:100,@0.1.3# triggered an error back from the router: !V:2,C:100,@0.1.3=10#.
2025-07-21 16:31:58.003 ERROR (MainThread) [aiohelvar.router] Request command >V:2,C:100,@0.1.4# triggered an error back from the router: !V:2,C:100,@0.1.4=10#.

`
```

and from the 2nd router too:


```
2025-07-21 16:37:04.832 ERROR (MainThread) [custom_components.helvar.router] Unknown error connecting with Helvar router at 192.168.0.11
Traceback (most recent call last):
  File "/config/custom_components/helvar/router.py", line 43, in async_setup
    await router.initialize()
  File "/usr/local/lib/python3.13/site-packages/aiohelvar/router.py", line 207, in initialize
    await self.get_scenes()
  File "/usr/local/lib/python3.13/site-packages/aiohelvar/router.py", line 222, in get_scenes
    await get_scenes(self, self.groups)
  File "/usr/local/lib/python3.13/site-packages/aiohelvar/scenes.py", line 74, in get_scenes
    parts = response.result.strip("@").split("@")
            ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strip'
2025-07-21 16:37:05.951 ERROR (MainThread) [aiohelvar.router] Request command >V:2,C:100,@0.1.1# triggered an error back from the router: !V:2,C:100,@0.1.1=10#.
2025-07-21 16:37:05.969 ERROR (MainThread) [aiohelvar.router] Request command >V:2,C:100,@0.1.2# triggered an error back from the router: !V:2,C:100,@0.1.2=10#.
2025-07-21 16:37:05.972 ERROR (MainThread) [aiohelvar.router] Request command >V:2,C:100,@0.1.3# triggered an error back from the router: !V:2,C:100,@0.1.3=10#.
2025-07-21 16:37:05.974 ERROR (MainThread) [aiohelvar.router] Request command >V:2,C:100,@0.1.4# triggered an error back from the router: !V:2,C:100,@0.1.4=10#.


```

**Comment by 1aranzant** [comment]
@tomplayford I updated to 0.2.1, now the logs show the following:

```
2025-07-22 14:30:12.333 ERROR (MainThread) [custom_components.helvar.config_flow] Creating Helvar config entry
NoneType: None
2025-07-22 14:30:17.443 WARNING (MainThread) [aiohelvar.scenes] No scene names returned from router
2025-07-22 14:30:17.468 ERROR (MainThread) [homeassistant.components.select] Error adding entity select.group_none for domain select with platform helvar
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohelvar/scenes.py", line 44, in get_scene
    return self.scenes[scene_address]
           ~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: None
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 657, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 979, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1370, in add_to_platform_finish
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1019, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1141, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1081, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1025, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 145, in state
    current_option = self.current_option
                     ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/helvar/select.py", line 46, in current_option
    current_scene = self.router.api.scenes.get_scene(current_scene_address)
  File "/usr/local/lib/python3.13/site-packages/aiohelvar/scenes.py", line 48, in get_scene
    f"Scene not found: {scene_address} (group={scene_address.group}, "
                                               ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

```


`Encountered unknown DALI device type of ['0x1', '0x0', '0x0', '0x0']
`

```
Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohelvar/groups.py", line 191, in update_group_last_scene
    scene_address = SceneAddress(
        group_id, *blockscene_to_block_and_scene(block_scene)
    )
  File "/usr/local/lib/python3.13/site-packages/aiohelvar/parser/address.py", line 134, in __init__
    self.block = block
    ^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohelvar/parser/address.py", line 162, in block
    raise TypeError("Block must be between 1 and 8.")
TypeError: Block must be between 1 and 8.

```


```
Request command >V:2,C:100,@0.10.2# triggered an error back from the router: !V:2,C:100,@0.10.2=11#.
Request command >V:2,C:100,@0.10.3# triggered an error back from the router: !V:2,C:100,@0.10.3=11#.
Request command >V:2,C:100,@0.10.4# triggered an error back from the router: !V:2,C:100,@0.10.4=11#.

```

**Comment by tomplayford** [comment]
Thanks for testing this. The exception parsing still has some stupid errors - but the underlying error is that there seem to be no scenes in the router, yet a scene selector component is trying to get the state of a scene that doesn't exist. Hard for me to test this as I can't replicate. 

The second error seems similar. 

Are you comfortable using an interactive python shell? If so, please connect to the router using `aiohevlar` alone (check out the example) and try and retrieve all the scenes there.

**Comment by 1aranzant** [comment]
@tomplayford I'm not sure what to replace in HelvarAddress:
`    device_address_to_flash = HelvarAddress(0, 1, 1, 14)`

If I run your simple_example.py with these settings:
```
    router_ip_address = "192.168.0.10"
    router_helvarnet_port = 50000
    device_address_to_flash = HelvarAddress(0, 1, 1, 14)
```

I get the following:

```
Connecting to router at address: 192.168.0.10...
Connected to router on workgroup: workgroup.
Initializing router...
No scene names returned from router
Router devices: 
Router groups: 
    Group 0: None. Has 0 devices.
    Group 1: None. Has 0 devices.
    Group 2: None. Has 0 devices.
    Group 3: None. Has 0 devices.
    Group 4: None. Has 0 devices.
    Group 5: None. Has 0 devices.
    Group 6: None. Has 0 devices.
    Group 7: None. Has 0 devices.
    Group 8: None. Has 0 devices.
    Group 9: None. Has 0 devices.
    Group 10: None. Has 0 devices.
    Group 11: None. Has 0 devices.
    Group 19: None. Has 0 devices.
    Group 20: None. Has 0 devices.
    Group 21: None. Has 0 devices.
    Group 22: None. Has 0 devices.
Router scenes: 
    @0.1.1: None
    @0.1.2: None
    @0.1.3: None
    @0.1.4: None
    @0.1.5: None
    @0.1.6: None
    @0.1.7: None
[.........]
    @22.8.13: None
    @22.8.14: None
    @22.8.15: None
    @22.8.16: None
Couldn't find device with address: @0.1.1.14
Task exception was never retrieved
future: <Task finished name='Task-57' coro=<Devices.set_device_load_level.<locals>.task() done, defined at c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\devices.py:277> exception=KeyError(<aiohelvar.parser.address.HelvarAddress object at 0x0000029D2F850D70>)>
Traceback (most recent call last):
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\devices.py", line 291, in task
    await devices.update_device_load_level(address, load_level)
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\devices.py", line 225, in update_device_load_level
    await self._update_device_param(address, "load_level", float(load_level))
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\devices.py", line 249, in _update_device_param
    setattr(self.devices[address], param, value)
            ~~~~~~~~~~~~^^^^^^^^^
KeyError: <aiohelvar.parser.address.HelvarAddress object at 0x0000029D2F850D70>
Task exception was never retrieved
future: <Task finished name='Task-7' coro=<get_groups.<locals>.update_group_last_scene() done, defined at c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py:172> exception=TypeError('Block must be between 1 and 8.')>
Traceback (most recent call last):
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py", line 191, in update_group_last_scene
    scene_address = SceneAddress(
        group_id, *blockscene_to_block_and_scene(block_scene)
    )
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 134, in __init__
    self.block = block
    ^^^^^^^^^^
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 162, in block
    raise TypeError("Block must be between 1 and 8.")
TypeError: Block must be between 1 and 8.
Task exception was never retrieved
future: <Task finished name='Task-10' coro=<get_groups.<locals>.update_group_last_scene() done, defined at c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py:172> exception=TypeError('Block must be between 1 and 8.')>
Traceback (most recent call last):
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py", line 191, in update_group_last_scene
    scene_address = SceneAddress(
        group_id, *blockscene_to_block_and_scene(block_scene)
    )
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 134, in __init__
    self.block = block
    ^^^^^^^^^^
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 162, in block
    raise TypeError("Block must be between 1 and 8.")
TypeError: Block must be between 1 and 8.
Task exception was never retrieved
future: <Task finished name='Task-13' coro=<get_groups.<locals>.update_group_last_scene() done, defined at c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py:172> exception=TypeError('Block must be between 1 and 8.')>
Traceback (most recent call last):
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py", line 191, in update_group_last_scene
    scene_address = SceneAddress(
        group_id, *blockscene_to_block_and_scene(block_scene)
    )
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 134, in __init__
    self.block = block
    ^^^^^^^^^^
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 162, in block
    raise TypeError("Block must be between 1 and 8.")
TypeError: Block must be between 1 and 8.
Task exception was never retrieved
future: <Task finished name='Task-16' coro=<get_groups.<locals>.update_group_last_scene() done, defined at c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py:172> exception=TypeError('Block must be between 1 and 8.')>
Traceback (most recent call last):
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py", line 191, in update_group_last_scene
    scene_address = SceneAddress(
        group_id, *blockscene_to_block_and_scene(block_scene)
    )
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 134, in __init__
    self.block = block
    ^^^^^^^^^^
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 162, in block
    raise TypeError("Block must be between 1 and 8.")
TypeError: Block must be between 1 and 8.
Task exception was never retrieved
future: <Task finished name='Task-19' coro=<get_groups.<locals>.update_group_last_scene() done, defined at c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py:172> exception=TypeError('Block must be between 1 and 8.')>
Traceback (most recent call last):
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py", line 191, in update_group_last_scene
    scene_address = SceneAddress(
        group_id, *blockscene_to_block_and_scene(block_scene)
    )
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 134, in __init__
    self.block = block
    ^^^^^^^^^^
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 162, in block
    raise TypeError("Block must be between 1 and 8.")
TypeError: Block must be between 1 and 8.
Task exception was never retrieved
future: <Task finished name='Task-22' coro=<get_groups.<locals>.update_group_last_scene() done, defined at c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py:172> exception=TypeError('Block must be between 1 and 8.')>
Traceback (most recent call last):
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py", line 191, in update_group_last_scene
    scene_address = SceneAddress(
        group_id, *blockscene_to_block_and_scene(block_scene)
    )
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 134, in __init__
    self.block = block
    ^^^^^^^^^^
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 162, in block
    raise TypeError("Block must be between 1 and 8.")
TypeError: Block must be between 1 and 8.
Task exception was never retrieved
future: <Task finished name='Task-25' coro=<get_groups.<locals>.update_group_last_scene() done, defined at c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py:172> exception=TypeError('Block must be between 1 and 8.')>
Traceback (most recent call last):
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py", line 191, in update_group_last_scene
    scene_address = SceneAddress(
        group_id, *blockscene_to_block_and_scene(block_scene)
    )
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 134, in __init__
    self.block = block
    ^^^^^^^^^^
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 162, in block
    raise TypeError("Block must be between 1 and 8.")
TypeError: Block must be between 1 and 8.
Task exception was never retrieved
future: <Task finished name='Task-28' coro=<get_groups.<locals>.update_group_last_scene() done, defined at c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py:172> exception=TypeError('Block must be between 1 and 8.')>
Traceback (most recent call last):
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py", line 191, in update_group_last_scene
    scene_address = SceneAddress(
        group_id, *blockscene_to_block_and_scene(block_scene)
    )
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 134, in __init__
    self.block = block
    ^^^^^^^^^^
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 162, in block
    raise TypeError("Block must be between 1 and 8.")
TypeError: Block must be between 1 and 8.
Task exception was never retrieved
future: <Task finished name='Task-31' coro=<get_groups.<locals>.update_group_last_scene() done, defined at c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py:172> exception=TypeError('Block must be between 1 and 8.')>
Traceback (most recent call last):
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py", line 191, in update_group_last_scene
    scene_address = SceneAddress(
        group_id, *blockscene_to_block_and_scene(block_scene)
    )
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 134, in __init__
    self.block = block
    ^^^^^^^^^^
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 162, in block
    raise TypeError("Block must be between 1 and 8.")
TypeError: Block must be between 1 and 8.
Task exception was never retrieved
future: <Task finished name='Task-34' coro=<get_groups.<locals>.update_group_last_scene() done, defined at c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py:172> exception=TypeError('Block must be between 1 and 8.')>
Traceback (most recent call last):
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py", line 191, in update_group_last_scene
    scene_address = SceneAddress(
        group_id, *blockscene_to_block_and_scene(block_scene)
    )
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 134, in __init__
    self.block = block
    ^^^^^^^^^^
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 162, in block
    raise TypeError("Block must be between 1 and 8.")
TypeError: Block must be between 1 and 8.
Task exception was never retrieved
future: <Task finished name='Task-37' coro=<get_groups.<locals>.update_group_last_scene() done, defined at c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py:172> exception=TypeError('Block must be between 1 and 8.')>
Traceback (most recent call last):
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py", line 191, in update_group_last_scene
    scene_address = SceneAddress(
        group_id, *blockscene_to_block_and_scene(block_scene)
    )
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 134, in __init__
    self.block = block
    ^^^^^^^^^^
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 162, in block
    raise TypeError("Block must be between 1 and 8.")
TypeError: Block must be between 1 and 8.
Task exception was never retrieved
future: <Task finished name='Task-40' coro=<get_groups.<locals>.update_group_last_scene() done, defined at c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py:172> exception=TypeError('Block must be between 1 and 8.')>
Traceback (most recent call last):
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py", line 191, in update_group_last_scene
    scene_address = SceneAddress(
        group_id, *blockscene_to_block_and_scene(block_scene)
    )
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 134, in __init__
    self.block = block
    ^^^^^^^^^^
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 162, in block
    raise TypeError("Block must be between 1 and 8.")
TypeError: Block must be between 1 and 8.
Task exception was never retrieved
future: <Task finished name='Task-43' coro=<get_groups.<locals>.update_group_last_scene() done, defined at c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py:172> exception=TypeError('Block must be between 1 and 8.')>
Traceback (most recent call last):
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py", line 191, in update_group_last_scene
    scene_address = SceneAddress(
        group_id, *blockscene_to_block_and_scene(block_scene)
    )
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 134, in __init__
    self.block = block
    ^^^^^^^^^^
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 162, in block
    raise TypeError("Block must be between 1 and 8.")
TypeError: Block must be between 1 and 8.
Task exception was never retrieved
future: <Task finished name='Task-46' coro=<get_groups.<locals>.update_group_last_scene() done, defined at c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py:172> exception=TypeError('Block must be between 1 and 8.')>
Traceback (most recent call last):
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py", line 191, in update_group_last_scene
    scene_address = SceneAddress(
        group_id, *blockscene_to_block_and_scene(block_scene)
    )
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 134, in __init__
    self.block = block
    ^^^^^^^^^^
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 162, in block
    raise TypeError("Block must be between 1 and 8.")
TypeError: Block must be between 1 and 8.
Task exception was never retrieved
future: <Task finished name='Task-49' coro=<get_groups.<locals>.update_group_last_scene() done, defined at c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py:172> exception=TypeError('Block must be between 1 and 8.')>
Traceback (most recent call last):
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py", line 191, in update_group_last_scene
    scene_address = SceneAddress(
        group_id, *blockscene_to_block_and_scene(block_scene)
    )
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 134, in __init__
    self.block = block
    ^^^^^^^^^^
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 162, in block
    raise TypeError("Block must be between 1 and 8.")
TypeError: Block must be between 1 and 8.
Task exception was never retrieved
future: <Task finished name='Task-52' coro=<get_groups.<locals>.update_group_last_scene() done, defined at c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py:172> exception=TypeError('Block must be between 1 and 8.')>
Traceback (most recent call last):
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\groups.py", line 191, in update_group_last_scene
    scene_address = SceneAddress(
        group_id, *blockscene_to_block_and_scene(block_scene)
    )
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 134, in __init__
    self.block = block
    ^^^^^^^^^^
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\parser\address.py", line 162, in block
    raise TypeError("Block must be between 1 and 8.")
TypeError: Block must be between 1 and 8.
Encountered unknown DALI device type of ['0x1', '0x0', '0x0', '0x0']
Encountered unknown DALI device type of ['0x1', '0x0', '0x0', '0x0']
Request command >V:2,C:100,@0.10.2# triggered an error back from the router: !V:2,C:100,@0.10.2=11#.
Request command >V:2,C:100,@0.10.3# triggered an error back from the router: !V:2,C:100,@0.10.3=11#.
Request command >V:2,C:100,@0.10.4# triggered an error back from the router: !V:2,C:100,@0.10.4=11#.
Exception handling line from router: ('!V:2,C:14,L:0.0,F:100,@0.1.1.14=10#', "Couldn't identify parameter pair in string: ")
Exception handling line from router: ('!V:2,C:14,L:0.0,F:100,@0.1.1.14=0#', "Couldn't identify parameter pair in string: ")
Couldn't find device with address: @0.1.1.14
Task exception was never retrieved
future: <Task finished name='Task-278' coro=<Devices.set_device_load_level.<locals>.task() done, defined at c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\devices.py:277> exception=KeyError(<aiohelvar.parser.address.HelvarAddress object at 0x0000029D2F850D70>)>
Traceback (most recent call last):
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\devices.py", line 291, in task
    await devices.update_device_load_level(address, load_level)
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\devices.py", line 225, in update_device_load_level
    await self._update_device_param(address, "load_level", float(load_level))
  File "c:\Users\Thibault\Downloads\aiohelvar-0.9.7\aiohelvar-0.9.7\aiohelvar\devices.py", line 249, in _update_device_param
    setattr(self.devices[address], param, value)
            ~~~~~~~~~~~~^^^^^^^^^
KeyError: <aiohelvar.parser.address.HelvarAddress object at 0x0000029D2F850D70>
Exception handling line from router: ('!V:2,C:14,L:100,F:100,@0.1.1.14=10#', "Couldn't identify parameter pair in string: ")
Exception handling line from router: ('!V:2,C:14,L:100,F:100,@0.1.1.14=0#', "Couldn't identify parameter pair in string: ")
```

Yet I can see all my groups and devices in Designer...

<img width="1448" height="509" alt="Image" src="https://github.com/user-attachments/assets/6b5980bd-ea7d-4681-a811-731f11fa50b7" />

**Comment by 1aranzant** [comment]
@tomplayford strange behavior... the HACS integration was able to get some of the groups/devices. But none of them work. 
Sometimes I can control the devices, but I never had the state returned. 

<img width="971" height="362" alt="Image" src="https://github.com/user-attachments/assets/f018ab87-28c2-492e-bd6c-a4190bbd7b06" />

<img width="805" height="1476" alt="Image" src="https://github.com/user-attachments/assets/fb3b5910-6fa0-4e26-8f75-9d1183177286" />
